defaults: &defaults
  nus_money_for_champion: 1000000
  final_match_time: "2022/12/18 22:00:00 +7"
  group_stage:
    start: 2022/11/19
    end: 2022/12/03
  round_of_16:
    start: 2022/12/03
    end: 2022/12/07
  quarter_final:
    start: 2022/12/08
    end: 2022/12/11
  semi_final:
    start: 2022/12/13
    end: 2022/12/15
  third_fourth:
    start: 2022/12/16
    end: 2022/12/17
  final:
    start: 2022/12/17
    end: 2022/12/18
  predict_champion_deadline:
    first: "2022/11/20 22:30:00 +7"
    second: "2022/12/03 21:30:00 +7"
    third: "2022/12/09 21:30:00 +7"
  predict_champion_money:
    first: 100000
    second: 150000
    third: 200000
  top_scores_report_match_id:
    first_round_group_stage: 16
    second_round_group_stage: 32
    third_round_group_stage: 48
    round_of_16: 56
    quarter_final: 60
    semi_final: 62
    third_fourth: 63
    final: 64
  is_demo: false
  boss_contribute:
  #   -
  #     game_id: 1
  #     money: 1000000
  #   -
  #     game_id: 37
  #     money: 1000000
  sponsor_contribute:
  #   -
  #     game_id: 51
  #     money: 2000000
  #     name: Đại gia Hiệp Nguyễn-Hoàng
development:
  <<: *defaults
  group_mails:
    - 'staff@nustechnology.com'
    - 'internship.dev@nustechnology.com'
    - 'internship.ba_qc@nustechnology.com'
    - 'thieunguyen.it@gmail.com'
    - 'hoanghiep.stt@gmail.com'
  neat_setting: 800
  is_turn_off_mail: false

test:
  <<: *defaults

production:
  <<: *defaults
  group_mails:
    - 'staff@nustechnology.com'
    - 'internship.dev@nustechnology.com'
    - 'internship.ba_qc@nustechnology.com'
    - 'thieunguyen.it@gmail.com'
    - 'hoanghiep.stt@gmail.com'
  is_turn_off_mail: false
