defaults: &defaults
  nus_money_for_champion: 1000000
  final_match_time: "2018/07/15 22:00:00 +7"
  group_stage:
    start: 2018/06/13
    end: 2018/06/29
  round_of_16:
    start: 2018/06/29
    end: 2018/07/04
  quarter_final:
    start: 2018/07/05
    end: 2018/07/08
  semi_final:
    start: 2018/07/10
    end: 2018/07/12
  third_fourth:
    start: 2018/07/13
    end: 2018/07/14
  final:
    start: 2018/07/14
    end: 2018/07/15
  predict_champion_deadline:
    first: "2018/06/14 21:30:00 +7"
    second: "2018/06/30 20:30:00 +7"
    third: "2018/07/06 20:30:00 +7"
  predict_champion_money:
    first: 100000
    second: 150000
    third: 200000
  top_scores_report_match_id:
    first_round_group_stage: 16
    second_round_group_stage: 32
    third_round_group_stage: 48
    round_of_16: 56
    quarter_final: 60
    semi_final: 62
    final: 64
  is_demo: true

development:
  <<: *defaults
  staffs_group_mail: 'staff@example.com'
  group_mails: ['staff@example.com', 'internship.dev@example.com', 'internship.ba_qc@example.com']
  group_mails_with_hr: ['hr@example.com', 'staff@example.com', 'internship.dev@example.com', 'internship.ba_qc@example.com']
  neat_setting: 800
  is_turn_off_mail: false

test:
  <<: *defaults

production:
  <<: *defaults
  staffs_group_mail: 'staff@nustechnology.com'
  group_mails: ['staff@nustechnology.com', 'internship.dev@nustechnology.com', 'internship.ba_qc@nustechnology.com']
  group_mails_with_hr: ['hr@nustechnology.com', 'staff@nustechnology.com', 'internship.dev@nustechnology.com', 'internship.ba_qc@nustechnology.com']
  is_turn_off_mail: false
  sendgrid:
    username: thieunv182
    password: il0v3r0r182