defaults: &defaults
  nus_money_for_champion: 1000000
  final_match_time: "2016/07/11 02:00:00 +7"
  group_stage:
    start: 2016/06/10
    end: 2016/06/23
  round_of_16:
    start: 2016/06/25
    end: 2016/06/28
  quarter_final:
    start: 2016/06/30
    end: 2016/07/04
  semi_final:
    start: 2016/07/06
    end: 2016/07/08
  final:
    start: 2016/07/10
    end: 2016/07/11
  predict_champion_deadline:
    first: "2016/06/10 17:15:00 +7"
    second: "2016/06/25 20:00:00 +7"
    third: "2016/07/01 02:00:00 +7"
  predict_champion_money:
    first: 100000
    second: 150000
    third: 200000

development:
  <<: *defaults
  staffs_mail_group: 'staff@example.com'
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
  staffs_mail_group: 'vanthieuuit@gmail.com'
  sendgrid:
    username: jackulti
    password: il0v3r0r182