defaults: &defaults
  nus_money_for_champion: 1000000
  final_match_time: "2021/07/12 02:00:00 +7"
  group_stage:
    start: 2021/06/12
    end: 2021/06/24
  round_of_16:
    start: 2021/06/26
    end: 2021/06/30
  quarter_final:
    start: 2021/07/02
    end: 2021/07/04
  semi_final:
    start: 2021/07/07
    end: 2021/07/08
  # third_fourth:
  #   start: 2021/07/13
  #   end: 2021/07/14
  final:
    start: 2021/07/11
    end: 2021/07/12
  predict_champion_deadline:
    first: "2021/06/12 01:30:00 +7"
    second: "2021/06/26 22:30:00 +7"
    third: "2021/07/02 22:30:00 +7"
  predict_champion_money:
    first: 100000
    second: 150000
    third: 200000
  top_scores_report_match_id:
    first_round_group_stage: 12
    second_round_group_stage: 24
    third_round_group_stage: 36
    round_of_16: 44
    quarter_final: 48
    semi_final: 50
    # third_fourth: 63
    final: 51
  is_demo: false
  boss_contribute:
    -
      game_id: 1
      money: 1000000
    -
      game_id: 37
      money: 1000000

development:
  <<: *defaults
  group_mails:
    - 'staff@nustechnology.com'
    - 'internship.dev@nustechnology.com'
    - 'internship.ba_qc@nustechnology.com'
    - 'thieunguyen.it@gmail.com'
    - 'hoanghiep.stt@gmail.com'
  neat_setting: 800
  is_turn_off_mail: false

test:
  <<: *defaults

production:
  <<: *defaults
  group_mails:
    - 'staff@nustechnology.com'
    - 'internship.dev@nustechnology.com'
    - 'internship.ba_qc@nustechnology.com'
    - 'thieunguyen.it@gmail.com'
    - 'hoanghiep.stt@gmail.com'
  is_turn_off_mail: false
